name: "Pull Request Docs Build"
on: [pull_request, push]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependenciees
      run: | 
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y pandoc
        python -m sphinx build -b html source build
        pwd
        ls -a .
        ls -a ./build
    - uses: actions/upload-artifact@v1
      with:
        name: github-pages
        path: /home/runner/work/AllMyNotes/AllMyNotes/build/
    - name: Commit HTML output to gh-pages
      run: |
          ls -a .
          git clone https://github.com/horsewithnoname1985/AllMyNotes.git --branch gh-pages --single-branch gh-pages
          cp -r ./build/* gh-pages/
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
    # - name: Deploy
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./build/html
        
  # deploy:
  #   needs: docs
  #   # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
  #   permissions:
  #     pages: write      # to deploy to Pages
  #     id-token: write   # to verify the deployment originates from an appropriate source
      
  #   # Deploy to the github-pages environment
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}

  #   # Specify runner + deployment step
  #   runs-on: ubuntu-latest
  #   steps:
  #     uses: peaceiris/actions-gh-pages@v3
  #       # uses: actions/upload-pages-artifact@v3
  #     with:
  #       publish_dir: ./build/html
          # Upload entire repository
          # path: './build'
      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v1 # or specific "vX.X.X" version tag for this action
