name: "Pull Request Docs Build"
on: [pull_request, push]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependenciees
      run: | 
        pip install -r requirements.txt
        sudo apt-get update
        apt apt-get install -y pandoc
    - name: Build documentation
      run: python -m sphinx build -b html source build
