name: "Pull Request Docs Build"
on: [pull_request, push]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "."
        python-version: '3.11'
        build-command: "python -m sphinx build -b html source build"
